
pingpong-dispatcher:
	@cc -Wall pingpong-scheduler.c ppos_core.c queue.c -o pingpong-scheduler

debug:
	@cc -Wall -DDEBUG pingpong-scheduler.c ppos_core.c queue.c -o pingpong-scheduler


clean:
	@rm pingpong-scheduler
