
pingpong-dispatcher:
	@cc -Wall pingpong-dispatcher.c ppos_core.c queue.c -o pingpong-dispatcher

debug:
	@cc -Wall -DDEBUG pingpong-dispatcher.c ppos_core.c queue.c -o pingpong-dispatcher


clean:
	@rm pingpong-dispatcher
